### ISSUE TITLE
Add support for response_format in OpenAiAudio

### ISSUE THREAD

**Issue by deepahmc** [KeyserDSoze/Rystem.OpenAi#100]
### Describe the feature or improvement you're requesting

I would like to get the word level timestamps for the transcriptions. I couldn't specify the vtt or the srt format in my requests.

**Comment by KeyserDSoze** [comment]
Hi, in the latest release tonight i've added the segmentation for transcription and translation.
You can read it as segments or words.
![image](https://github.com/user-attachments/assets/9eba00f0-c6f0-4839-b2c2-bd702f90c778)

For example you can get the full text and the segments that compound it.

![image](https://github.com/user-attachments/assets/304b0f8f-a2b6-4a32-8110-79d0974f253f)

You can do the same for translation.
![image](https://github.com/user-attachments/assets/e37aef5c-846d-47f3-82c8-060f8c5b36fc)

**Comment by deepahmc** [comment]
Would it be possible to include the fix in the version compatible with .NTE 8.0? Thank you!
