### ISSUE TITLE
SetGpt4With8KPrice is set with 32k Model

### ISSUE THREAD

**Issue by chr0mcom** [KeyserDSoze/Rystem.OpenAi#38]
### Describe the bug

Method SetGpt4With8KPrice in Class OpenAiPriceSettings:
-> https://github.com/KeyserDSoze/Rystem.OpenAi/blob/9644d92ee681526eead5fdd5acd007f48fa416bb/src/Rystem.OpenAi.Api/Utilities/Cost/OpenAiCostSettings.cs#L66

Must be changed in 8k Model

### To Reproduce

Description above is all u need to fix

### OS

Windows

### .Net version

.net 7

### Library version

3.3.1

**Comment by KeyserDSoze** [comment]
Fixed in release 3.3.2
