### ISSUE TITLE
Add new Interface IOpenAiChatFunction<T> so that WrapAsync does not have to be cast from object

### ISSUE THREAD

**Issue by lukasschachner** [KeyserDSoze/Rystem.OpenAi#45]
### Describe the feature or improvement you're requesting

In order to use the Type information about the function you are calling and its return type the interface should also be generic,

My proposal is to expose the interface as 
```csharp
public interface IOpenAiChatFunction<T>
{
        // omitted for brevity
	Task<T> WrapAsync(string message);
}
```

**Comment by KeyserDSoze** [comment]
I moved this functionality on Rystem.PlayFramework with a brand new experience.
