### ISSUE TITLE
New fine-tuning endpoint support

### ISSUE THREAD

**Issue by minzdrav** [KeyserDSoze/Rystem.OpenAi#56]
### Describe the feature or improvement you're requesting

Hello there,
Could you please add support for the new fine-tuning endpoint?
Migration from legacy endpoint - https://platform.openai.com/docs/guides/fine-tuning/migration-of-legacy-models
New endpoint documentation - https://platform.openai.com/docs/guides/fine-tuning
https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates

Thank you!

**Comment by KeyserDSoze** [comment]
new version is available with this fix. Thanks.

**Comment by minzdrav** [comment]
Hi @KeyserDSoze 
Sorry, the endpoint doesn't work. You made a mistake in the URL. Should be "fine_tuning", but you entered "fine-tuning".
Could you please release the fix?
![image](https://github.com/KeyserDSoze/Rystem.OpenAi/assets/1764392/736b852d-36b6-4c93-b5f3-0552844f6055)

**Comment by KeyserDSoze** [comment]
Sorry. I updated the endpoint and now the solution is online with new version 3.3.6

**Comment by minzdrav** [comment]
@KeyserDSoze 
new error - invalid batch_size, extra fields not permitted.
Looks like the request and response models are a bit different and additional fields are not supported by API.
You can find model descriptions here: https://platform.openai.com/docs/api-reference/fine-tuning/object
Could you please remove unsupported fields and add new fields?
![image](https://github.com/KeyserDSoze/Rystem.OpenAi/assets/1764392/dbeec3ad-04f1-493a-8b5e-3841905ad6b1)

**Comment by minzdrav** [comment]
Hi @KeyserDSoze 
JSONL file should contain at least 10 lines. I was sent 1 line for testing and the job failed. In this case, API returns null in the trained_tokens field. Could you please allow null?
![image](https://github.com/KeyserDSoze/Rystem.OpenAi/assets/1764392/1e9062c2-9935-49ae-b6c5-fa460a43f740)

**Comment by minzdrav** [comment]
With 10 lines trained_tokens  is null too, because it's not yet trained.

**Comment by minzdrav** [comment]
[TestOpenAIFineTuning.zip](https://github.com/KeyserDSoze/Rystem.OpenAi/files/12981011/TestOpenAIFineTuning.zip)
code example

**Comment by minzdrav** [comment]
![image](https://github.com/KeyserDSoze/Rystem.OpenAi/assets/1764392/782a1a78-616c-467a-853d-2fe68b96cf84)
finished_at field is missing in FineTuneResult

**Comment by minzdrav** [comment]
Thank you! It's ok now :)

**Comment by minzdrav** [comment]
@KeyserDSoze sorry, man. One more important field is missing in FineTuneResult - fine_tuned_model. Without this field, I can't identify trained model.

**Comment by KeyserDSoze** [comment]
new version is live, the property was present but it was an object, now it's correctly a string?

**Comment by minzdrav** [comment]
Thank you! Yes, it's string now.
