### ISSUE TITLE
Delete model (fine-tuned)

### ISSUE THREAD

**Issue by minzdrav** [KeyserDSoze/Rystem.OpenAi#64]
### Describe the feature or improvement you're requesting

Hi @KeyserDSoze 
Could you please add a delete model API?
Docs: https://platform.openai.com/docs/api-reference/models/delete

**Comment by KeyserDSoze** [comment]
I've added with the last release this feature.

### Delete fine-tune model
Delete a fine-tuned model. You must have the Owner role in your organization.

    var openAiApi = _openAiFactory.Create(name);
    var deleteResult = await openAiApi.Model
        .DeleteAsync(fineTuneModelId);

**Comment by minzdrav** [comment]
Cool! Thank you!
