### ISSUE TITLE
Stop processing when a function is called

### ISSUE THREAD

**Issue by Aspyryan** [KeyserDSoze/Rystem.OpenAi#69]
### Describe the feature or improvement you're requesting

I am trying to use a function to know when my chatbot is not going to respond with an answer because it does not have enough context. I know the openai functions work by providing the function result and retrying the call. I want the initial call to stop when the function is called so I can return my own custom response to the user. How would I achieve this?

### Additional context

Code right now:
```cs
public async IAsyncEnumerable<CostResult<StreamingChatResult>> GetStreamedChatCompletion(ChatMessage[] chatMessages, CancellationToken cancellationToken)
{
	var openAiApi = _openAiFactory.Create("Azure");



	await foreach (var x in openAiApi.Chat
			.Request(chatMessages)
			.WithModel(ChatModelType.Gpt35Turbo)
			.WithFunction(NoAnswerFunction.NameLabel)
			.ExecuteAsStreamAndCalculateCostAsync(cancellationToken: cancellationToken))
	{
		yield return x;
	}
}
internal sealed class NoAnswerFunction : IOpenAiChatFunction
{
	public const string NameLabel = "no_answer";
	public string Name => NameLabel;
	private const string DescriptionLabel = "Er kan geen antwoord op de vraag worden geformuleerd op basis van de gegeven context.";
	public string Description => DescriptionLabel;
	public Type Input => typeof(NoAnswerRequest);
	public async Task<object> WrapAsync(string message)
	{
		return new NoAnswerResponse();
	}
}
internal sealed class NoAnswerRequest { }
internal sealed class NoAnswerResponse { }
```

**Comment by simetelum** [comment]
Looks like this: https://github.com/KeyserDSoze/Rystem.OpenAi/discussions/37

**Comment by Aspyryan** [comment]
Yea but the finishreason when streaming is always null and only "stop" on the last chunk, there is never a function chunk or something that I can do processing on.

**Comment by KeyserDSoze** [comment]
I think you can use the autoExecuteFunction to true to allow the framework works and if openai will think it's correct to stop the execution to call a function, directly the framework will execute the call to your method.
If you created a correct function. You only need to add 
```
.ExecuteAsStreamAndCalculateCostAsync(true, cancellationToken);
```

**Comment by KeyserDSoze** [comment]
I've removed this functionality from Rystem.OpenAi and move it as a framework on Rystem.PlayFramework.
