### ISSUE TITLE
Get back more information from the Audio endpoint

### ISSUE THREAD

**Issue by TomasEkeli** [KeyserDSoze/Rystem.OpenAi#73]
### Describe the feature or improvement you're requesting

The audio endpoint exposes just the transcribed/tranlsated text, if we need more information (segments, probabilities, etc) this library cannot be used.

I have created a pull-request #72 with a suggested change that creates two new methods `VerboseTranscribeAsync` and `VerboseTranslateAsync`. These return a `VerboseAudioResult` that contains segments and such. The only difference in the actual call is to request a `verbose_json` format.

**Comment by KeyserDSoze** [comment]
I've added your PR, and added two types of Verbosity, one for segments, and one for words.

![image](https://github.com/user-attachments/assets/50759606-8780-445e-a1b1-488b57d8729e)
