### ISSUE TITLE
CreateChatCompletionWithFunctionsAsync Failing

### ISSUE THREAD

**Issue by NickDevoctomy** [KeyserDSoze/Rystem.OpenAi#85]
### Describe the bug

I'm trying to run the CreateChatCompletionWithFunctionsAsync test as I can't get the function feature to work in my own code, but the same error is occurring with the test.

It fails on the response containing the tool message.

### To Reproduce

1. Run CreateChatCompletionWithFunctionsAsync  test against OpenAI
2. Notice exception occurs on second ( response = await request.ExecuteAndCalculateCostAsync(); )

Error:

{
  "error": {
    "message": "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.",
    "type": "invalid_request_error",
    "param": "messages.[1].role",
    "code": null
  }
}

### OS

Windows

### .Net version

.Net 8

### Library version

Latest master

**Comment by KeyserDSoze** [comment]
In the new version 4.0.0 this issue is solved.
