### ISSUE TITLE
Mark Repository And Packages as Deprecated

### ISSUE THREAD

**Issue by taylorchasewhite** [KeyserDSoze/Rystem.OpenAi#88]
### Describe the feature or improvement you're requesting

Folks coming here to use this library should realize that it is no longer being maintained.

**Comment by KeyserDSoze** [comment]
I'm currently working on a huge update of this library. I'm adding a new framework to deal with tools and functions. New package Rystem.PlayFramework will be available soon. Today I released the pre-release for Rystem.OpenAi and Rystem.PlayFramework.
